### ISSUE TITLE
用户逻辑相关问题

### ISSUE THREAD

**Issue by FranGuam** [eesast/web#1645]
这个`issue`汇总在用户逻辑**测试过程中遇到的`bug`和体验不好的点**

**所有人**在不重复的前提下都可以追加问题，负责解决这些问题的`PR`请引用这个`issue`

**Comment by FranGuam** [comment]
- [ ] 使用不在数据库中的邮箱登录时提示`未知错误`
- [ ] 验证码错误不会当场提示，而是在最后操作时提示

**Comment by BlitherBoom812** [comment]
- [ ]  代码提交窗口只有一个编译状态，却有5个编译信息，应该要么都是1个，要么都是5个。
- [ ] 代码提交窗口的编译按钮不太显眼，在右下角。感觉可以放在标题下面，或者放在表格上面，一眼就能看到。

**Comment by youyc22** [comment]
> * [ ] **用户信息页面UI美化**
> * [ ] **添加自定义头像功能**

**Comment by FranGuam** [comment]
> * [ ]  **添加自定义头像功能**

再开新issue作为下一届的饼吧，这个issue我先关了
