### ISSUE TITLE
赛事代码管理相关问题

### ISSUE THREAD

**Issue by FranGuam** [eesast/web#1647]
这个`issue`汇总在队式代码**测试过程中遇到的`bug`和体验不好的点**

**所有人**在不重复的前提下都可以追加问题，负责解决这些问题的`PR`请引用这个`issue`

**Comment by FranGuam** [comment]
@BlitherBoom812 新开了一个`issue`，可以在这边提，这样分类清晰一些 =》

**Comment by FranGuam** [comment]
- [ ] 数据库`contest_code`表采取同一队只存一个条目的策略，从`code1`到`code6`存储多列，难以应对可能的code数量变化，考虑改成`code + num`的记录形式，可拓展性更好
- [ ] `contest_code`的文件路径使用绝对路径完整记录，实际可以只记录`code_id`拼出路径，动态性更好

**Comment by BlitherBoom812** [comment]
神了

**Comment by BlitherBoom812** [comment]
> * [ ]  数据库`contest_code`表采取同一队只存一个条目的策略，从`code1`到`code6`存储多列，难以应对可能的code数量变化，考虑改成`code + num`的记录形式，可拓展性更好
> * [ ]  `contest_code`的文件路径使用绝对路径完整记录，实际可以只记录`code_id`拼出路径，动态性更好

如果以后路径的接口还要修改，在现有条件下只需要修改前端（前端指定 cos 路径并上传代码，前端记录上传的绝对路径）。仅记录 `code_id` 的情况下需要同时修改前端和后端（前端指定 cos 路径并上传代码，后端解析上传的绝对路径），耦合度上升了，感觉保留路径更好。或者上传代码和路径管理全部移到后端来做，也可减小耦合。

**Comment by FranGuam** [comment]
> > * [ ]   数据库`contest_code`表采取同一队只存一个条目的策略，从`code1`到`code6`存储多列，难以应对可能的code数量变化，考虑改成`code + num`的记录形式，可拓展性更好
> > * [ ]   `contest_code`的文件路径使用绝对路径完整记录，实际可以只记录`code_id`拼出路径，动态性更好
> 
> 对于第二点，如果以后路径的接口还要修改，在现有条件下只需要修改前端（前端指定 cos 路径并上传代码，前端记录上传的绝对路径）。仅记录 `code_id` 的情况下需要同时修改前端和后端（前端指定 cos 路径并上传代码，后端解析上传的绝对路径），耦合度上升了，感觉保留路径更好。或者上传代码和路径管理全部移到后端来做，也可减小耦合。

你说得有道理，耦合度的确上升了。不过耦合度的上升可以通过统一规范解决，问题在于如果cos储存文件结构变了，数据库里的绝对路径很难调整，这是我担心的地方。如果上传代码直接交给后端倒也是不错的方案，我支持。

**Comment by BlitherBoom812** [comment]
> > > * [ ]    数据库`contest_code`表采取同一队只存一个条目的策略，从`code1`到`code6`存储多列，难以应对可能的code数量变化，考虑改成`code + num`的记录形式，可拓展性更好
> > > * [ ]    `contest_code`的文件路径使用绝对路径完整记录，实际可以只记录`code_id`拼出路径，动态性更好
> > 
> > 
> > 对于第二点，如果以后路径的接口还要修改，在现有条件下只需要修改前端（前端指定 cos 路径并上传代码，前端记录上传的绝对路径）。仅记录 `code_id` 的情况下需要同时修改前端和后端（前端指定 cos 路径并上传代码，后端解析上传的绝对路径），耦合度上升了，感觉保留路径更好。或者上传代码和路径管理全部移到后端来做，也可减小耦合。
> 
> 你说得有道理，耦合度的确上升了。不过耦合度的上升可以通过统一规范解决，问题在于如果cos储存文件结构变了，数据库里的绝对路径很难调整，这是我担心的地方。如果上传代码直接交给后端倒也是不错的方案，我支持。

有道理，这样数据库确实减少了调整负担。主要在于cos的文件结构可以批量修改，而hasura大概只能跑几千条脚本一个个改，成本太高。 cos 也是要手改的，也挺麻烦。这样看全部移到后端可能是最好的做法了，后端可以定义一个 get_code_path 路径生成函数，无论是上传还是下载都用同一个路径函数。

**Comment by xiangmy21** [comment]
Bug Report:
- [ ] 上传按钮无法上传代码
