### ISSUE TITLE
赛事其他问题

### ISSUE THREAD

**Issue by FranGuam** [eesast/web#1649]
这个`issue`汇总在队式其他**测试过程中遇到的`bug`和体验不好的点**

可以包括：
- 管理员操作逻辑
- UI数据呈现
- 公告和静态资源管理等

**所有人**在不重复的前提下都可以追加问题，负责解决这些问题的`PR`请引用这个`issue`

**Comment by FranGuam** [comment]
- [ ] 建议将所有管理员操作（如导出队伍信息、发布公告）整合到统一的管理员页面，而非分散在各页难以管理

**Comment by FranGuam** [comment]
- [ ] 建议为管理员提供更多数据可视化的界面（如已有多少队伍提交了代码、某一角色的赢率是多少）方便队式组做出决策

**Comment by FranGuam** [comment]
- [ ] 赛事`ListPage`感觉比较单调，希望呈现更多信息（如主题图、时间线、比赛特色等）

**Comment by zzdhybthu** [comment]
- [ ] 管理员编辑比赛信息表单缺少自动填充功能，导致修改比赛信息费时费力

**Comment by ljxuann** [comment]
编辑公告的权限需要修改，目前所有人都可编辑

**Comment by zzdhybthu** [comment]
- [ ] 现在报名-管理队伍-加入队伍/创建队伍有时点不了

**Comment by zzdhybthu** [comment]
- [ ] 天梯试炼-对战记录点击报错

**Comment by FranGuam** [comment]
> * [ ]  天梯试炼-对战记录点击报错

分类错误，建议移至 #1648

**Comment by youyc22** [comment]
> * [ ]  现在报名-管理队伍-加入队伍/创建队伍有时点不了，和role无关

已修改

**Comment by youyc22** [comment]
> * [ ]  天梯试炼-对战记录点击报错

已解决

> * [ ]  现在报名-管理队伍-加入队伍/创建队伍有时点不了，和role无关

已解决
