### ISSUE TITLE
奖助学金申请相关问题

### ISSUE THREAD

**Issue by FranGuam** [eesast/web#1652]
这个`issue`汇总在奖助学金**测试过程中遇到的`bug`和体验不好的点**

**所有人**在不重复的前提下都可以追加问题，负责解决这些问题的`PR`请引用这个`issue`

**Comment by lqs22yeah** [comment]
奖助学金——申请荣誉——填好申请资料后弹出Uncaught runtime errors页面并显示“申请提交失败”
