### ISSUE TITLE
Info 2020 需要补充/修改的地方

### ISSUE THREAD

**Issue by robertying** [eesast/web#393]
- [ ] 为新生导师申请的提交、状态更新等设置 event trigger（参考旧 repo）；

- [ ] 考虑如何增加设置项，让老师能够选择“接收”或“不接收”新生导师申请中与导师交流信息的邮件提醒（设置 event trigger，如需接收则发送邮件）；

- [ ] 完整联调测试。

- [ ] 申请记录导出和导入过程可能还需要优化（极大可能存在 bug 或者使用性问题！）。需要考虑，导入导出时，用户的识别是通过学号（id）还是 ObjectId（_id）进行？记录的识别是通过记录内学生学号还是记录自身的 id 进行？需要做到导入方便，也不能产生太大的数据一致性问题。（现在的版本只是有个框架，细节问题还未考虑）

- [ ] 常用 student_id 表示 ObjectId，是否会和普通的学号 id 混淆？

**Comment by Sweetnow** [comment]
### 新需求

#### 新生导师

- [ ] 支持添加新生导师的简介，类似于推研平台的教师端，或利用爬虫从ee.tsinghua.edu.cn上自动拉取导师信息并展示。
