### ISSUE TITLE
Info 2020 推研平台需要修改的地方

### ISSUE THREAD

**Issue by Sweetnow** [eesast/web#431]
- [x] 只有“已确认”的学生申请提交才需要审核。
- [x] 将“有意向/已联络/已确认”的学生数量放到老师列表中，方便浏览。
- [x] 为学生用户提供查看自己的申请状态的页面，并提供撤销操作。
- [ ] 辅导员（审核）和老师可以查看报名同学的姓名，其中辅导员可以查看任意老师的情况，老师只能查看自己的情况。
- [ ] 为学生用户提供找到提交申请入口的指引。

**Comment by duskmoon314** [comment]
- [ ] 显式博士名额
- [ ]  “博士生招生信息”
- [ ]  只审核已确认，其他提示“提交成功”
- [ ] 研究方向 => 研究所
- [ ] 查看审核通过的信息
- [ ] 关于名额的提示信息
- [ ] 导师可以修改、删除信息，需要审核
